<script lang="ts">
	import '$lib/main.css';
	import { onMount } from 'svelte';
	let theme = 'dark';

	const switchTheme = () => {
		if (theme === 'light') {
			theme = 'dark';
		} else {
			theme = 'light';
		}
	};

	onMount(() => {
		theme = window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
	});
</script>

<div id="container" class:dark={theme === 'dark'}>
	<header>
		<div id="title">
			<h1>Northernlion chatalytics</h1>
			<p>NL stream highlights, generated by chat.</p>
		</div>
		<div id="menu">
			<p>
				<a href="/">Home</a>
			</p>
			<p>
				<a href="/about">About</a>
			</p>
			<p>
				<a href="/donate">Donate</a>
			</p>
		</div>
		<div
			id="dark-mode-toggle"
			role="button"
			tabindex="0"
			class:dark={theme === 'dark'}
			on:click={switchTheme}
			on:keypress={switchTheme}
		>
			<span class:theme-active={theme === 'dark'}>d</span>
			|
			<span class:theme-active={theme === 'light'}>l</span>
		</div>
	</header>

	<slot />
</div>

<style>
	header {
		display: flex;
		flex-direction: row;
		padding: 0 2em;
		padding-bottom: 0;
		border-bottom: 1px solid var(--border-color);
		max-height: 100%;
	}

	#menu {
		display: flex;
		flex-direction: row;
		align-items: center;
		justify-content: center;
		flex-grow: 1;
	}

	#menu > p {
		align-self: flex-center;
		font-size: larger;
	}

	#menu > p {
		margin: 0;
	}

	#menu a:visited {
		color: var(--text-color);
	}

	#menu > p:not(:last-child):after {
		margin: 0 1em;
		content: ' | ';
	}
	h1 {
		font-size: 24px;
		margin-bottom: 10px;
	}

	p {
		font-size: 16px;
	}

	@media (max-width: 600px) {
		header {
			flex-direction: column;
		}

		#menu {
			margin-top: 1em;
		}
	}
</style>
